services:
  conduit-frontend:
    image: ghcr.io/zeebuhh/conduit-frontend:latest
    ports:
      - "8282:80"
    env_file:
      - .env
    restart: on-failure

  conduit-backend:
    image: ghcr.io/zeebuhh/conduit-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static:/app/static
      - media:/app/media
    restart: on-failure

volumes:
  static:
  media:
