name: Build, Push und Deployment

on:
  push:
    branches:
      - Zeebuhh-patch-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login on GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build und Push conduit-frontend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/conduit-frontend:latest ./conduit-frontend
          docker push ghcr.io/${{ github.repository_owner }}/conduit-frontend:latest
      - name: Build und Push conduit-backend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/conduit-backend:latest ./conduit-backend
          docker push ghcr.io/${{ github.repository_owner }}/conduit-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH Deployment
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Conduit-Compose-Setup
            git pull origin Zeebuhh-patch-1
            docker-compose down
            docker-compose pull
            docker-compose up -d
